version: '3.8'

services:
  whisper-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WHISPER_MODEL_SIZE=small  # Change to tiny, small, medium, large-v2, large-v3 as needed
      - WHISPER_CACHE_DIR=/app/models
    volumes:
      - whisper_models:/app/models  # Persist downloaded models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  whisper_models: