# Minimal docker-compose for Proxmox/Portainer deployment
version: '3.8'

services:
  whisper-ai-cpu:
    # Use pre-built image from Docker Hub (built via GitHub Actions)
    image: earlysvahn/whisper-transcribe-api:latest
    container_name: whisper-ai-test
    ports:
      - "8765:8000"
    environment:
      - WHISPER_MODEL_SIZE=tiny  # Use tiny model for low-resource environments
      - WHISPER_CACHE_DIR=/app/models
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    volumes:
      - whisper_models_cpu:/app/models  # Persist downloaded models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s  # Longer start period for slow CPU
    # Resource limits for Proxmox
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  whisper_models_cpu:
    driver: local