name: Build and Deploy Docker Images to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push CPU-optimized image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.cpu
        push: true
        build-args: |
          BUILD_VERSION=${{ github.run_number }}
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
        tags: |
          earlysvahn/whisper-transcribe-api:latest
          earlysvahn/whisper-transcribe-api:cpu

    - name: Build and push GPU-enabled image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          earlysvahn/whisper-transcribe-api:gpu